# .github/workflows/deploy.yml
name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # Or whatever your primary branch is

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necessary to push the built site to the gh-pages branch
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # Fetches the Hugo theme submodule
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build Hugo Site
        run: |
          cd hugo_docs
          hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Publish the whole repo
          # The user who pushes the commit to the gh-pages branch
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
